### ISSUE TITLE
Configurable menu on click on user avatar in header

### ISSUE THREAD

**Issue by theliuk** [micro-lc/micro-lc#451]
At the moment, in the page header, upon clicking on the user avatar, a menu with only one CTA is shown, and the action is "disconnect".
<img width="147" alt="Schermata 2022-03-15 alle 09 55 03" src="https://user-images.githubusercontent.com/809858/158341447-dcaf705e-0984-448c-89cc-9b82c061fe52.png">

It'd be useful to be able to configure other CTAs, like a simple link to the profile section.

**Comment by amountainram** [comment]
not relevant here

must evolve this guy [here](https://git.tools.mia-platform.eu/platform/backoffice/back-kit/bk-web-components/-/blob/main/packages/web-components/src/components/misc/layout/bk-layout.ts)
