### ISSUE TITLE
Add options to inject external sytlesheet into plugins

### ISSUE THREAD

**Issue by AndreaMaffe** [micro-lc/micro-lc#500]
## Problem ##
Currently, `micro-lc` allows to orchestrate micro-frontends coming from different sources, but since these micro-frontens can vary a lot in UI design, there is a high risk to obtain a overall result which lacks in visual consistency (expecially when the injected plugins offer low to zero support for UI customization). 

## Proposal ##
A solution for the issue could be to offer the possibility of injecting a custom stylesheet for the plugins, either at general level (e.g. in the `theming` section of the config) or inside the configuration of the specific plugin. The former solution could be better for consistency, since the same style is defined only once, but the latter could allow a higher level of precision and avoid to mix styles that are intended to be effective only on a specific micro-fe.

The stylesheet could be injected either by typing directly the CSS code inside the configuration (see example below) or by contacting a specific url passed in the configuration. The first solution is maybe simpler, but could lead to messy configuration if the number of CSS rules to be applied is high.

```
// example of a configuration
{
  "theming": {
    "header": {
      "pageTitle": "Test",
      "favicon": "https://www.test.it/favicon"
    },
    "logo": {
        ....
    },
    "customCSS": {
        "button.my-button": {
             "background-color": "red",
             "color": "FFFFFF",
             ...
        }
    }
```
Eventually, `micro-lc` could then apply specific prefixes to the provided selectors to increment the specificity of the rules:
```
// example of the result CSS rule
#micro-lc-container button.my-button {
     background-color: red;
     color: "FFFFFF";
     ...
}
```

**Comment by theliuk** [comment]
We are really looking forward for this feature. At the moment there's no way to make styles coherent across all the backoffice application.

**Comment by ilteoood** [comment]
Yesterday I've with @AndreaMaffe a web component from scratch to do this.
If @giulioroggero approves, we can make it OSS, otherwise we can leave this open and will be implemented in future versions of micro-lc.
