### ISSUE TITLE
Error During Installation of "@micro-lc/orchestrator"

### ISSUE THREAD

**Issue by riteshakya037** [micro-lc/micro-lc#937]
**Description**
I encountered an issue while installing `"@micro-lc/orchestrator"` version `2.4.1`. My project uses `pnpm`. The installation process warns about a 404 error for the "ajv-format" package.

**Environment**

I'm using micro-lc version 2.4.1
I'm serving configurations using @micro-lc/orchestrator at version 2.4.1

**Minimal Reproduction**
- Create a new project using pnpm.
- Attempt to install "@micro-lc/orchestrator" version 2.4.1.
- Observe the warning about the 404 error for the "ajv-format" package.

**Additional context**
Error with `pnpm`
![image](https://github.com/micro-lc/micro-lc/assets/9533579/df429682-2481-4c77-a8c2-136a5cd04512)

It appears that the peer dependency is specified as `"ajv-format": ">=2.1.1"` in the "@micro-lc/orchestrator" package.json file, as seen [here](https://github.com/micro-lc/micro-lc/blob/1d13d2a372ab67018e677071227127198fcd51d9/packages/orchestrator/package.json#L93).

```json
  "peerDependencies": {
    "ajv": ">=8.11.0",
    "ajv-format": ">=2.1.1",
    "es-module-shims": ">=1.5.3"
  },
  ```

**Suggested Solution**
Update the peer dependency from "ajv-format" to "ajv-formats" in the "@micro-lc/orchestrator" package.json file.

**Comment by amountainram** [comment]
Thanks for the heads-up! Fixing soon

**Comment by riteshakya037** [comment]
> Thanks for the heads-up! Fixing soon

Much appreciated 🙏

**Comment by amountainram** [comment]
the `@micro-lc/orchestrator@2.4.2` patch for the orchestrator should fix the issue
